<a href="https://colab.research.google.com/github/ChungJaeYeom/DataScienceLife/blob/main/06_09_02_%ED%85%8D%EC%8A%A4%ED%8A%B8_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BeautifulSoup 사용하여 HTML 파싱

In [ ]:
from bs4 import BeautifulSoup
from urllib.request import urlopen

# 문자열에서 soup을 생성한다.
soup1 = BeautifulSoup("<HTML><HEAD><<headers>></HEAD><<body>></HTML>")

# 로컬 파일에서 soup을 생성한다. -> myDoc.html 파일을 사용
soup2 = BeautifulSoup(open("myDoc.html"))

# 웹문서에서 soup을 생성한다. -> 크롤링의 기초
soup3 = BeautifulSoup(urlopen("http://www.networksciencelab.com/"))

In [ ]:
soup1

<html><head></head><body><p>&lt;<headers>&gt;&lt;&gt;</headers></p></body></html>

In [ ]:
soup2

<html><head></head><body><p>&lt;<headers>&gt;&lt;&gt;</headers></p></body></html>

In [ ]:
soup3

<html>
<head>
<title>My Little Network Science Lab</title>
<link href="style.css" rel="stylesheet" type="text/css"/>
<meta charset="utf-8"/>
</head>
<body>
<h1>My Little Network Science Lab</h1>
<h2>By Dmitry Zinoviev</h2>
<p>
</p><table class="hdr"><tr><td><h3 class="nomargin">Books</h3></td></tr></table>
<p>
<a href="https://pragprog.com/book/dzpyds/data-science-essentials-in-python"><img align="left" border="1" src="https://imagery.pragprog.com/products/490/dzpyds_xlargecover.jpg?1468006361"/></a>
<a href="https://pragprog.com/book/dzcnapy/complex-network-analysis-in-python"><img align="left" border="1" src="https://imagery.pragprog.com/products/541/dzcnapy_xlargecover.jpg?1508250011"/></a>


I am excited to announce my books, "Data Science Essentials in Python. Collect →  Organize →  Explore →  Predict →  Value" (a.k.a. DZPYDS) and "Complex Network Analysis in Python. Recognize → Construct → Visualize → Analyze → Interpret" (a.k.a. DZCNAPY), published by the Pragmatic Bookshelf.
</

find(),find_all() 특정 속성 (href= 파이퍼링크 정보) 값 찾기

In [ ]:
# http://www.networksciencelab.com/ 사이트에서 하이퍼 링크 정보 모두 가져오기

with urlopen("http://www.networksciencelab.com/") as doc:
  soup = BeautifulSoup(doc)

# 하이퍼 링크 추출
links = [(link.string, link["href"]) for link in soup.find_all("a") if link.has_attr("href")]
links
# 튜플 리스트로 가져옴

[(None, 'https://pragprog.com/book/dzpyds/data-science-essentials-in-python'),
 (None,
  'https://pragprog.com/book/dzcnapy/complex-network-analysis-in-python'),
 ('DZPYDS', 'https://www.amazon.com/gp/product/1680501844'),
 ('DZCNAPY', 'https://www.amazon.com/gp/product/1680502697'),
 ('Networks of Music Groups as Success Predictors',
  'http://www.slideshare.net/DmitryZinoviev/networks-of-music-groups-as-success-predictors'),
 ('Network Science Workshop',
  'http://www.slideshare.net/DmitryZinoviev/workshop-20212296'),
 ('Resilience in Transaction-Oriented Networks',
  'http://www.slideshare.net/DmitryZinoviev/resilience-in-transactional-networks'),
 ('Peer Ratings in Massive Online Social Networks',
  'http://www.slideshare.net/DmitryZinoviev/peer-ratings-in-massive-online-social-networks'),
 ('Semantic Networks of Interests in Online NSSI Communities',
  'http://www.slideshare.net/DmitryZinoviev/presentation-31680572'),
 ('Towards an Ideal Store',
  'http://www.slideshare.net/Dmitry

In [ ]:
# http://www.networksciencelab.com/ 사이트에서 하이퍼 링크 정보 모두 가져오기

with urlopen("https://sejong.korea.ac.kr/kr") as doc:
  soup = BeautifulSoup(doc)

# 하이퍼 링크 추
links = [(link.string, link["href"]) for link in soup.find_all("a") if link.has_attr("href")]
links
# 튜플 리스트로 가져옴

CSV 파일 다루기

statistics 모듈을 사용해서 나이 변수의 평균과 표준편차 구하기

데이터 가져오기





In [ ]:
import csv

with open("/content/Demographic_Statistics_By_Zip_Code.csv") as infile:
  data = list(csv.reader(infile))

In [ ]:
#data 다 확인
# 첫번째 레코드에 COUNT PARTICIPANTS 데이터 인덱스 값 추출 data[0] 컬럼 값
countParticipantsIndex = data[0].index("COUNT PARTICIPANTS")
countParticipantsIndex


1

In [ ]:
# COUNT PARTICIPANTS 데이터 추출

countParticipants = [int(row[countParticipantsIndex]) for row in data[1:]] #리스트 내포
countParticipants #작은 따옴표가 없다 -> 숫자로 잘 들어왔다.

나이의 평균과 표준편차

In [ ]:
import statistics

print(statistics.mean(countParticipants), statistics.stdev(countParticipants))

17.661016949152543 43.27973735299687


자연어 처리하기

In [ ]:
pip install nltk

In [ ]:
import nltk
nltk.__version__

'3.2.5'

nltk 에서 영단어 온톨로지(wordnet) 사용하기

In [ ]:
#https://frhyme.github.io/python-lib/nltk-wordnet/
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
wn = nltk.corpus.wordnet #코퍼스 리더(reader)

#sysnet: 유의어 묶음으로 단어-품사-순번 으로 구성
wn.synsets("cat") #sets는 목차 여러개..

[Synset('cat.n.01'),
 Synset('guy.n.01'),
 Synset('cat.n.03'),
 Synset('kat.n.01'),
 Synset('cat-o'-nine-tails.n.01'),
 Synset('caterpillar.n.02'),
 Synset('big_cat.n.01'),
 Synset('computerized_tomography.n.01'),
 Synset('cat.v.01'),
 Synset('vomit.v.01')]

In [ ]:
wn.synset('cat.n.01').hypernyms() #hypernyms 상위어

[Synset('feline.n.01')]

In [ ]:
wn.synset('cat.n.01').hyponyms() #hyponyms 하위어

[Synset('domestic_cat.n.01'), Synset('wildcat.n.03')]

WordNet 사용해서 synset간 의미론적 유사도 계산하기 (0-1사이 실수)

0이면 두 단어 서로 관계 없음
1이면 완전한 유의어

In [ ]:
# 고양이, 링스; 시라소니 유사도 계산
x = wn.synset('cat.n.01') # 고양이
y = wn.synset('lynx.n.01') # 시라소니

# x,y 유사도 계산
x.path_similarity(y)

0.04

In [ ]:
x = wn.synset('cat.n.01') #고양이
y = wn.synset('domestic_cat.n.01') #집고양이
x.path_similarity(y)

0.5

In [ ]:
x = wn.synset('cat.n.01') #고양이
y = wn.synset('cat.n.01') #고양이
x.path_similarity(y)

1.0

In [ ]:
x = wn.synset('cat.n.01') #고양이
y = wn.synset('dog.n.01') #강아지
x.path_similarity(y)

0.2

In [ ]:
wn.synset('dog.n.01').hyponyms()

[Synset('basenji.n.01'),
 Synset('corgi.n.01'),
 Synset('cur.n.01'),
 Synset('dalmatian.n.02'),
 Synset('great_pyrenees.n.01'),
 Synset('griffon.n.02'),
 Synset('hunting_dog.n.01'),
 Synset('lapdog.n.01'),
 Synset('leonberg.n.01'),
 Synset('mexican_hairless.n.01'),
 Synset('newfoundland.n.01'),
 Synset('pooch.n.01'),
 Synset('poodle.n.01'),
 Synset('pug.n.01'),
 Synset('puppy.n.01'),
 Synset('spitz.n.01'),
 Synset('toy_dog.n.01'),
 Synset('working_dog.n.01')]

In [ ]:
from nltk.tokenize import WordPunctTokenizer
word_punct = WordPunctTokenizer()

text = "}Help! :))) :[ ..... :D{"

# Tokenizer는 모든 구두점(punctuation: 문장부호)을 기준으로 분리
# -> 이모티콘을 이용한 감성 분석 등 문장구조 깊이 분석 할 때 사용

word_punct.tokenize(text)

['}', 'Help', '!', ':)))', ':[', '.....', ':', 'D', '{']

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
# word 토크나이저는 다 분비시킨다.
nltk.word_tokenize(text)

['}', 'Help', '!', ':', ')', ')', ')', ':', '[', '...', '..', ':', 'D', '{']

In [ ]:
# 2. 단어의 대소문자를 통일한다 (전부 다 대문자 or 소문자)
# 3. 불용어 제거 (stopwords 리스트 참조 THE 같은 것들 제거)
# 4. 형태소 분석(stemming) 단어를 형태소로 변환

#포터 형태소 분석기 (보수적)

pstemmer = nltk.PorterStemmer()
pstemmer.stem("wonderful")

'wonder'

In [ ]:
#랭커스터 형태소 분석기 (적극적) - 더 많은 동음이의어 형태소 생산

lstemmer = nltk.LancasterStemmer()
lstemmer.stem("wonderful")

'wond'

In [ ]:
#5. 원형 추출

lemmatizer = nltk.WordNetLemmatizer()
lemmatizer.lemmatize("wonderful")

'wonderful'

In [ ]:
# 그외 품사 태깅

nltk.download('averaged_perceptron_tagger')
nltk.pos_tag(["beautiful", "world"]) # JJ	adjective(형용사), NN	noun(명사)


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


[('beautiful', 'JJ'), ('world', 'NN')]

index.html 파일에서(불용어 제외) 가장 많이 등장한 단어 원형 찾아보기

In [ ]:
# www.networksciencelab.com 사이트에서 하이퍼 링크 정보 모두 가져오기

from bs4 import BeautifulSoup
from urllib.request import urlopen

with urlopen("http://www.networksciencelab.com/") as doc:
  soup = BeautifulSoup(doc)

# 하이퍼 링크 추출
links = [(link.string, link["href"]) for link in soup.find_all("a") if link.has_attr("href")]

# 책 제목만 추출
html_text = [i[0] for i in links]

# None 데이터 제거
html_text = " ".join(html_text[2:])
html_text

'DZPYDS DZCNAPY Networks of Music Groups as Success Predictors Network Science Workshop Resilience in Transaction-Oriented Networks Peer Ratings in Massive Online Social Networks Semantic Networks of Interests in Online NSSI Communities Towards an Ideal Store D.Zinoviev, "Analyzing Cultural Domains with Python," D. Zinoviev, D. Stefanescu, G. Fireman, and L. Swenson, "Semantic networks of interests in online non-suicidal self-injury communities," D.Zinoviev, "The Pain of Complexity," D.Zinoviev, Z.Zhu, and K.Li, "Building mini-categories in product networks," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Mitigation of delayed management costs in transaction-oriented systems," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Simulating resilience in transaction-oriented networks," D.Zinoviev, D.Stefanescu, L.Swenson, and G.Fireman, "Semantic networks of interests in online NSSI communities," D.Zinoviev and S.Llewelyn, "Co-Evolution of Friendship and Publishing in Online

In [ ]:
# index.html 파일로 저장
html_file = open("index.html",'w')
html_file.write(html_text)
html_file.close()

index.html 파일에서(불용어 제외) 가장 많이 등장한 단어 원형 찾아보기 

In [ ]:
from bs4 import BeautifulSoup
from collections import Counter
from nltk.corpus import stopwords
from nltk import LancasterStemmer

# 형태소 분류기를 생성한다.
ls = nltk.LancasterStemmer()

# 파일을 읽고 soup을 만든다.
with open("/content/index.html") as infile:
  soup = BeautifulSoup(infile)

In [ ]:
soup

<html><body><p>DZPYDS DZCNAPY Networks of Music Groups as Success Predictors Network Science Workshop Resilience in Transaction-Oriented Networks Peer Ratings in Massive Online Social Networks Semantic Networks of Interests in Online NSSI Communities Towards an Ideal Store D.Zinoviev, "Analyzing Cultural Domains with Python," D. Zinoviev, D. Stefanescu, G. Fireman, and L. Swenson, "Semantic networks of interests in online non-suicidal self-injury communities," D.Zinoviev, "The Pain of Complexity," D.Zinoviev, Z.Zhu, and K.Li, "Building mini-categories in product networks," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Mitigation of delayed management costs in transaction-oriented systems," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Simulating resilience in transaction-oriented networks," D.Zinoviev, D.Stefanescu, L.Swenson, and G.Fireman, "Semantic networks of interests in online NSSI communities," D.Zinoviev and S.Llewelyn, "Co-Evolution of Friendship and Publis

In [ ]:
soup.text #html로 받았지만 text로 접근할 수 있다.

'DZPYDS DZCNAPY Networks of Music Groups as Success Predictors Network Science Workshop Resilience in Transaction-Oriented Networks Peer Ratings in Massive Online Social Networks Semantic Networks of Interests in Online NSSI Communities Towards an Ideal Store D.Zinoviev, "Analyzing Cultural Domains with Python," D. Zinoviev, D. Stefanescu, G. Fireman, and L. Swenson, "Semantic networks of interests in online non-suicidal self-injury communities," D.Zinoviev, "The Pain of Complexity," D.Zinoviev, Z.Zhu, and K.Li, "Building mini-categories in product networks," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Mitigation of delayed management costs in transaction-oriented systems," D.Zinoviev, H.Benbrahim, G.Meszoely, and D.Stefanescu, "Simulating resilience in transaction-oriented networks," D.Zinoviev, D.Stefanescu, L.Swenson, and G.Fireman, "Semantic networks of interests in online NSSI communities," D.Zinoviev and S.Llewelyn, "Co-Evolution of Friendship and Publishing in Online

In [ ]:
# 1) 텍스트 추출 -> 토큰화
words = nltk.word_tokenize(soup.text)
words

In [ ]:
# 2) 단어를 소문자로 변환 > 첫글자가 대문자로 되어있다. 
words = [w.lower() for w in words]
words

In [ ]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# 3) 불용어를 제거하고 단어의 형태소를 추출
# isalnum() 함수는 알파벳 소문자-대문자, 알파벳([a-zA-Z])와 숫자[0-9]로만 구성되었는지 확인함
# 3-1) 불영어 제거 stopwords.words("english")
# 3-2) 특수기호 제거 isalnum()
words = [ls.stem(w) for w in words if w not in stopwords.words("english") and w.isalnum()]

In [ ]:
#4 ) 가장 빈번하게 등장하는 단어 10개 추출
freqs = Counter(words)
print(freqs.most_common(5))

[('network', 16), ('soc', 8), ('onlin', 7), ('inform', 4), ('gam', 4)]


10개의 양수로 된 간단한 numpy 배열 만들기

In [ ]:
import numpy as np

numbers = np.array(range(1,11), copy=True)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ones() -> 1, zeros() -> 0, empty() -> 아직 생성되지 않은 엔트리로 구성

https://numpy.org/doc/stable/reference/generated/numpy.array.html




In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움
ones = np.ones([2,4], dtype = np.int64)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 0으로 채움
zeros = np.zeros([2,4], dtype = np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열
empty = np.empty([2,4], dtype = np.int64)
empty

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

데이터 확인하기

In [ ]:
ones.shape

(2, 4)

In [ ]:
ones.ndim

2

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
numbers.dtype

dtype('int64')

arange(start,stop,step,dtype=None) 일정 간격으로 배열 생성하는 함수

In [ ]:
np_numbers = np.arange(2,5,0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

astype(dtype, casting="unsafe", copy=True) 아이템의 타입 변경해 주는 함수


In [ ]:
np_numbers.dtype

dtype('float64')

In [ ]:
np_numbers = np_numbers.astype(np.int)
np_numbers.dtype

dtype('int64')

reshape(d0, d1, ...) 대상 배열의 모양을 바꿔주는 함수


In [ ]:
# 몇 가지 S&P 주식 기호들
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
sap.shape #(8,) 1차원 배열을 뜻한당

(8,)

In [ ]:
sap2d = sap.reshape(2,4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
# 기존 배열과 새로운 배열의 아이템의 개수는 항상 동일 해야 함
# numpy 보존의 법칙 성립

sap3d = sap.reshape(2,2,2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap3d[0] # 1차원

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [ ]:
sap3d[1] # 2차원

array([['ACE', 'ATVI'],
       ['ADBE', 'ADT']], dtype='<U4')

데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing


In [ ]:
# 절대 음수 값이 와서는 안되는 데이터 셋 

dirty = np.array([9,4,1,-0.01,-0.02,-0.001])
whos_dirty = dirty < 0
whos_dirty

array([False, False, False,  True,  True,  True])

In [ ]:
dirty[whos_dirty] = 0 # 모든 음수값을 0으로 바꿈
dirty

array([9., 4., 1., 0., 0., 0.])

논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용


In [ ]:
linear = np.arange(-1,1.1,0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [ ]:
# -0.5 ~ 0.5 사이의 값만 -> 0으로 변경하고 싶음

whos_linear = (linear <= 0.5) & (linear >= -0.5)
whos_linear

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [ ]:
linear[whos_linear] = 0
linear

array([-1. , -0.8, -0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0.8,  1. ])

스마트 인덱싱

In [ ]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
# S&P 리스트에서 두번째, 세번째, 마지막 주식 기호를 추출
sap[[1,2,-1]] # 인덱싱 1 , 2, 마지막

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [ ]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap2d[:,[1]] # 대괄호 해주면 2차원 배열

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [ ]:
sap2d[:,1] # 대괄호 안해주면 1차원 배열

array(['ABT', 'ATVI'], dtype='<U4')

차원만 같다면 numpy에서는 사칙연산 가능 (그낭 더하기) -> 브로드캐스팅


In [ ]:
a = np.arange(4)
b = np.arange(1,5)

print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [ ]:
a+b

array([1, 3, 5, 7])

In [ ]:
a*5

array([ 0,  5, 10, 15])

In [ ]:
noise = np.eye(4) # I 행렬 (단위행렬)
noise

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
noise = np.eye(4) + 0.01 * np.random.random([4,4]) # I 행렬 (단위행렬)
noise

array([[1.00414629, 0.0069077 , 0.00973191, 0.00153786],
       [0.00463409, 1.00717833, 0.00771507, 0.00995135],
       [0.00273957, 0.00310762, 1.00455983, 0.004331  ],
       [0.00908686, 0.0047749 , 0.00839886, 1.0007955 ]])